//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackNadzor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCenters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataCenters()
        {
            this.Racks = new HashSet<Racks>();
        }
    
        public int DataCenterID { get; set; }
        public string DataCenterName { get; set; }
        public string DataCenterAddress { get; set; }
        public string DataCenterStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racks> Racks { get; set; }
    }
}
