//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackNadzor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices()
        {
            this.Ports = new HashSet<Ports>();
        }
    
        public int DeviceID { get; set; }
        public int DeviceDataCenters { get; set; }
        public string DeviceRackName { get; set; }
        public int DevicePositionInUnits { get; set; }
        public int DeviceSizeInUnits { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceManufacturer { get; set; }
        public string DeviceSerialNumber { get; set; }
        public int DeviceTypeID { get; set; }
        private string _deviceDomainName;

        public string DeviceDomainName
        {
            get
            {
                if (string.IsNullOrEmpty(_deviceDomainName))
                {
                    return "нет домена";
                }
                else
                {
                    return _deviceDomainName;
                }
            }
            set
            {
                _deviceDomainName = value;
            }
        }
        public string DeviceIP { get; set; }
        public Nullable<System.DateTime> DeviceInspectionDate { get; set; }
    
        public virtual DeviceTypes DeviceTypes { get; set; }
        public virtual Racks Racks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ports> Ports { get; set; }
    }
}
