//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackNadzor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ports()
        {
            this.PortConnections = new HashSet<PortConnections>();
            this.PortConnections1 = new HashSet<PortConnections>();
        }
    
        public int PortID { get; set; }
        public int DeviceID { get; set; }
        public string PortNumber { get; set; }
        public string PortSpeed { get; set; }
        public string PortType { get; set; }
        public string PortStatus { get; set; }
        public string MacAdress { get; set; }
    
        public virtual Devices Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortConnections> PortConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortConnections> PortConnections1 { get; set; }
    }
}
