//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackNadzor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortConnections
    {
        public int ConnectionID { get; set; }
        public int PortA_ID { get; set; }
        public int PortB_ID { get; set; }
        public string ConnectionType { get; set; }
    
        public virtual Ports Ports { get; set; }
        public virtual Ports Ports1 { get; set; }
    }
}
