//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackNadzor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racks()
        {
            this.Devices = new HashSet<Devices>();
        }
    
        public int RackDataCenterID { get; set; }
        public string RackName { get; set; }
        public string RackRow { get; set; }
        public int RackPosition { get; set; }
        public int RackTotalUnits { get; set; }
        public int RackDepth { get; set; }
    
        public virtual DataCenters DataCenters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devices> Devices { get; set; }
    }
}
