//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackNadzor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RackBDEntities : DbContext
    {
        private static RackBDEntities _context;

        public static RackBDEntities GetContext()
        {
            if(_context == null)
                return _context=new RackBDEntities();
            return _context;

        }


        public RackBDEntities()
            : base("name=RackBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataCenters> DataCenters { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<DeviceTypes> DeviceTypes { get; set; }
        public virtual DbSet<PortConnections> PortConnections { get; set; }
        public virtual DbSet<Ports> Ports { get; set; }
        public virtual DbSet<Racks> Racks { get; set; }
    }
}
